import { DATE_FORMAT_TYPES } from './types'

export const DATE_FORMAT_FORMATS = {
  [DATE_FORMAT_TYPES.FULL_DATE]: 'MMMM D, YYYY',
  [DATE_FORMAT_TYPES.MONTH_DAY_YEAR]: 'MMMM/DD/YYYY',
  [DATE_FORMAT_TYPES.DAY_MONTH_YEAR]: 'DD/MMMM/YYYY',
  [DATE_FORMAT_TYPES.YEAR_MONTH_DAY]: 'YYYY/MM/DD',
  [DATE_FORMAT_TYPES.RELATIVE]: 'Relative',
}
